test
MvRemmerden/homebrew-cask pull request #1
Opened 2023-07-26 09:34 UTC by MvRemmerden

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2023-07-26 09:39 UTC, fracazo requested changes
Review

2023-07-26 09:40 UTC, MvRemmerden commented on README.md
> +Slower, now:s
```suggestion
Slower, now: sss
```

Fixed it, can you have a look again?

2023-09-20 04:17 UTC, fracazo approved these changes
LGTM! Approved!

2023-09-20 04:17 UTC, fracazo commented on README.md
> +Slower, now:s
> Fixed it, can you have a look again?

Sure adding this single comment but using ^ enter

2023-11-04 01:02 UTC, closed without merging